# specify what image is needed to run our code
# we can use node alpine, a smaller version of node
FROM node:23-slim
# FROM node:18.15.0

# Specifies what directory has all of our code. 
# adds all our code to the image

WORKDIR /app

# specifies where the packages are so they can be installed
COPY package.json .

RUN npm install react@18.2.0 react-dom@18.2.0 --save-exact

# shell command
RUN npm install

COPY . .

# ARG AZURE_AD_CLIENT_ID
# ARG AZURE_AD_CLIENT_SECRET
# ARG AZURE_AD_TENANT_ID
# ARG NEXTAUTH_URL
# ARG DATABASE_URL

# ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
# ARG CLERK_SECRET_KEY
# ARG CLERK_SIGNING_SECRET

# ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL
# ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL

# ARG NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
# ARG NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL

# ARG NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
# ARG NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL

# ARG NEXT_PUBLIC_CLERK_REDIRECT_URI
# ARG OPENAI_API_KEY
# ARG DATABASE_URL

# ENV AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
# ENV AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
# ENV AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
# ENV NEXTAUTH_URL=${NEXTAUTH_URL}
# ENV DATABASE_URL=${DATABASE_URL}
# ENV OPENAI_API_KEY=${OPENAI_API_KEY}

# ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
# ENV CLERK_SECRET_KEY = ${CLERK_SECRET_KEY}
# ENV CLERK_SIGNING_SECRET = ${CLERK_SIGNING_SECRET}
# ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL = ${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
# ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL = ${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
# ENV NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = ${NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
# ENV NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL = ${NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL}
# ENV NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL = ${NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL}
# ENV NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL = ${NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL}
# ENV NEXT_PUBLIC_CLERK_REDIRECT_URI = ${NEXT_PUBLIC_CLERK_REDIRECT_URI}
# ENV OPENAI_API_KEY = ${OPENAI_API_KEY}

RUN npm install prisma

RUN npx prisma generate

RUN npm run build

# exec form, array of strings
CMD ["npm", "start"]